### ISSUE TITLE
Add Claro admin theme

### ISSUE THREAD

**Issue by malabya** [malabya/pfpc#1]
Add Claro administrative theme.
[https://drupal.org/project/claro](https://drupal.org/project/claro)

**Comment by harikagujjula** [comment]
Claro not able to composer. 
So, i am updating the gitignore file to include the themes/contrib folder, which is previously ignored.
Is this fine?

**Comment by malabya** [comment]
@harikagujjula Claro will be added core in 8.8. Will be taking up this issue once there is a release
