### ISSUE TITLE
Create CT News

### ISSUE THREAD

**Issue by malabya** [malabya/pfpc#20]
Create content type - News

| Label | Machine name | Widget type |
| ----- | --------------- | ------------- |
| Title | title | Entity title |
| Organisation | organisation | Taxonomy reference - Organisation |
| Topic | topic | Taxonomy reference - Topic |
| Featured | featured | Boolean |
| Shoulder text | shoulder_text | text area |
| Media | media | Media |
| Body | body | Formatted text area |

**Comment by harikagujjula** [comment]
Adding Topic as single reference?

**Comment by malabya** [comment]
@harikagujjula 
Adding Topic as single reference? 
It should be multi valued

text area widget is Text plain long field type?
Yes

Are we using Article CT body field? The field widget is: Formatted text long with Summary!
Use the existing body field

**Comment by malabya** [comment]
@harikagujjula Please re-arrange the fields in the order given in the issue
