### ISSUE TITLE
Fix error of missing main.js file

### ISSUE THREAD

**Issue by malabya** [malabya/pfpc#22]
Error message:
`Warning: file_get_contents(themes/custom/pfpc/scripts/main.js): failed to open stream: No such file or directory in Drupal\Core\Asset\JsOptimizer->optimize() (line 25 of core/lib/Drupal/Core/Asset/JsOptimizer.php).`

Fix: Add a `scripts/main.js` file in the `pfpc` theme.

**Comment by harikagujjula** [comment]
File itself is not there na. I saw this. I thought you have missed the file or might be working!
