### ISSUE TITLE
Install and Configure Layout Builder Restriction module

### ISSUE THREAD

**Issue by malabya** [malabya/pfpc#36]
Install and Configure Layout Builder Restriction module
https://www.drupal.org/project/layout_builder_enhancements

For Basic Page CT: Configure the Layout Builder to show only PFPC Grid Layout and enable Page Hero Text and Page Building Block components.

**Comment by harikagujjula** [comment]
Installed Layout builder Restrictions module and configured it for Basec page CT.
Layout - Only PFPC grid is shown.
Blocks - Will be able to configure only blocks of type Page Hero Text and Page Building Block.
